### ISSUE TITLE
Lose docs revert

### ISSUE THREAD

**Issue by mo3et** [LolitaSian/LolitaSian.github.io#2]
博主你好 我昨天在你之前gitee上的博客看到了 [计算机专业英语 第一章](https://lolitaann.gitee.io/2021/04/17/12%20%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%B8%93%E4%B8%9A%E8%8B%B1%E8%AF%AD%E7%AC%AC%E4%B8%80%E7%AB%A0/) 这篇文章，这篇文章让我得到很大的帮助，但是发现没有在你现在用的 Hexo Blog上看到，所以我 back 了一份下来，仅作本地保存，不会在别的地方发。  
我尝试通过博客里的微信联系你，想把文章的Markdown发给你，但是暂时没有回应。我怕我忘了，所以就在 issue 里面写吧。  
我把文章的 Markdown 上传到了 Github 的 [Gist](https://gist.github.com/Mo3et/8222aac9919169968cc31650671dc54f) ，你可以在上面获取 md File，然后 Push到新的 Blog 上(将文首的引用去除即可)  。我希望这样有用的文章不会因为框架迁移而丢失。
如果我的这个行为让你感到冒犯的话，我在此向你致以深深的歉意。  
我同时也很喜欢你写的文章，希望能继续看到优秀的文章啦！ 加油！  ^__^

**Comment by LolitaSian** [comment]
hexo就是用markdown写的。gitee的博客已经不用了，只用github了。
https://lolitasian.github.io/


那个系列的文章已经不写了😂我删掉了。
 
---Original---
From: "Monet ***@***.***&gt;
Date: 2022/8/30 23:55:36
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [LolitaSian/LolitaSian.github.io] Lose docs revert (Issue #2)




 
博主你好 我昨天在你之前gitee上的博客看到了 计算机专业英语 第一章 这篇文章，这篇文章让我得到很大的帮助，但是发现没有在你现在用的 Hexo Blog上看到，所以我 back 了一份下来。
 我尝试通过博客里的微信联系你，想把文章的Markdown发给你，但是暂时没有回应。我怕我忘了，所以就在 issue 里面写吧。
 我把文章的 Markdown 上传到了 Github 的 Gist ，你可以在上面获取 md File，然后 Push到新的 Blog 上(将文首的引用去除即可)  。我希望这样有用的文章不会因为框架迁移而丢失。
 如果我的这个行为让你感到冒犯的话，我在此向你致以深深的歉意。

**Comment by mo3et** [comment]
好的😀
